use_frameworks!

target 'aaa_Example' do
  pod 'aaa', :path => '../'

  target 'aaa_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
